# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7e499e32236377982a71e2421b7f88598a826640e6db59b5711b77ad9fcd57b0b9a1379526b0f9f7fda116478cbb9cb7314b79a6fd64957987ce07fe3271671

test:
  secret_key_base: 4422e8e07954ac5f0de44255a8d44fdc1679c53c905ec8a347814e910839b78a0062d5008c21a91e9fec3a52faddb81f80b8ff27061e662543d7ded2c0d65704

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
